version: "3"

# common properties
x-common: &common
  tty: true
  stdin_open: true

services:
  game-play:
    <<: *common
    build:
      context: ./game
      dockerfile: docker/play/Dockerfile
    env_file:
      - ./game/env/.env
      - ./game/env/play/.env
    # Allow container to connect to host machine.
    # Needed for the game client to connect to the browser.
    network_mode: host
    volumes:
      - ./assets:/app/assets

  game-record:
    <<: *common
    build:
      context: ./game
      dockerfile: docker/record/Dockerfile
    env_file:
      - ./game/env/.env
      - ./game/env/record/.env
    # Allow container to connect to host machine.
    # Needed for the game client to connect to the browser.
    network_mode: host
    volumes:
      - ./assets:/app/assets

  stig-train:
    <<: *common
    build:
      context: ./stig
      dockerfile: docker/Dockerfile
    entrypoint: ["python", "-m", "stig.cmd.train.main"]
    env_file:
      - ./stig/env/.env
    volumes:
      - ./stig:/app/stig
      - ./assets:/app/assets
    # Needed not to run out of memory.
    shm_size: "2g"

  stig-drive:
    <<: *common
    build:
      context: ./stig
      dockerfile: docker/Dockerfile
    entrypoint: ["python", "-m", "stig.cmd.drive.main"]
    env_file:
      - ./stig/env/.env
    volumes:
      - ./stig:/app/stig
      - ./assets:/app/assets
